export const Routes = {
    Main: '/',
    Instr: '/instr',
    Instrument: '/instrument/',
    Checkout: '/checkout',
    Contact: '/contacts',
    About: '/about',
    Register: '/register',
    Login: '/login',
    Pay: '/pay',
    Service: '/service',
    Delivery: '/delivery',
    Guitars: '/guitars',
    BassGuitars: '/bass-guitars',
    Synths: '/synthesizers',
    Drums: '/drums',
}